# -*- coding: utf-8 -*-
"""medical billing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W26i-Cm3LZ_I5ZN_s8mEdTcRjs3y0Hpu
"""

pip install pandas numpy

import pandas as pd

# Load the medical billing data from a CSV file
def load_data(file_path):
    try:
        data = pd.read_csv(file_path)
        print("Data loaded successfully.")

         # Print the actual column names to check for discrepancies
        print("Column names in the DataFrame:", data.columns)

        return data
    except Exception as e:
        print(f"Error loading data: {e}")
        return None

# Summarize billing data
def summarize_billing(data):
    total_billed = data['Billing Amount'].sum()


    print("Billing Summary:")
    print(f"Total Billed Amount: ${total_billed:.2f}")

def find_discrepancies(data):
    # Assume discrepancies are where 'Billing Amount' is greater than 0
    discrepancies = data[data['Billing Amount'] > 0]  # Changed this line
    if not discrepancies.empty:
        print("Discrepancies found in the following records:")
        print(discrepancies)
    else:
        print("No discrepancies found.")

# Main function
def main():
    file_path = input("Enter the path to the medical billing CSV file: ")
    billing_data = load_data(file_path)

    if billing_data is not None:
        summarize_billing(billing_data) # Call summarize_billing inside the if block
        find_discrepancies(billing_data)

if __name__ == "__main__":
    main() # Call the main function to execute the code